# Generated by Django 4.1.3 on 2023-02-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cup', '0002_category_commande_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
