# Generated by Django 4.1.3 on 2023-02-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cup', '0005_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foot', models.CharField(max_length=200)),
                ('date_added_foot', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added_foot'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_foot', models.CharField(max_length=200)),
                ('email_foot', models.EmailField(max_length=254)),
                ('telephone_foot', models.CharField(max_length=200)),
                ('adresse_foot', models.CharField(max_length=200)),
                ('ville_foot', models.CharField(max_length=200)),
                ('pays_foot', models.CharField(max_length=200)),
                ('date_commande_foot', models.DateTimeField(auto_now_add=True)),
                ('items_foot', models.CharField(max_length=300)),
                ('total_foot', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date_commande_foot'],
            },
        ),
        migrations.CreateModel(
            name='ProductFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_foot', models.CharField(max_length=200)),
                ('description_foot', models.TextField()),
                ('price_foot', models.FloatField()),
                ('image_foot', models.CharField(max_length=5000)),
                ('date_added_foot', models.DateTimeField(auto_now_add=True)),
                ('category_foot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_foot', to='World_Cup.categoryfoot')),
            ],
            options={
                'ordering': ['-date_added_foot'],
            },
        ),
    ]
