# Generated by Django 4.1.3 on 2023-02-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cup', '0009_categorynfl_commandenfl_productnfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
