# Generated by Django 4.1.3 on 2023-02-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cup', '0010_commande_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
